server:
  port: 8084
  error:
    path: "/error"
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
      

spring:
  jpa:
    generate-ddl: true
    show-sql: false
    
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${SPRING_JPA_DATABASE-PLATFORM}
        globally_quoted_identifiers: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    initialization-mode: always
    platform: ${SPRING_DATASOURCE_PLATFORM}
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: mahajanatul007@gmail.com
    password: 8055806284
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
  

