server:
  port: 8084
 
spring:
  jpa:
    generate-ddl: true
    show-sql: false
    
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${SPRING_JPA_DATABASE-PLATFORM}
        globally_quoted_identifiers: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    initialization-mode: always
    platform: ${SPRING_DATASOURCE_PLATFORM}
    
  

