server:
  port: 8084
 
spring:
  jpa:
    generate-ddl: true
    show-sql: false
    
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true

  datasource:
    url: jdbc:mysql://localhost:3306/hrms?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Matul_525
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver
    platform: org.hibernate.dialect.MySQL8Dialect

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
    
  

