server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db-dev-v1-doc?createDatabaseIfNotExist=true
    username: admin
    password: admin@123
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
    
  

