server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://db-dev-v1-doc.coqvpa6wm9ky.ap-south-1.rds.amazonaws.com:3306/test1254?createDatabaseIfNotExist=true
    username: admin
    password: Matul_525
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    generate-ddl: true
    show-sql: false

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
        show_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
    
  

